workflows:
  android-workflow:
    name: Android Build via EAS
    max_build_duration: 60
    environment:
      node: 18.17.0
      npm: 9.6.7
      java: 17
      vars:
        EXPO_TOKEN: "VkNJEL0mNvRoV36R5vDeYPT4eSLJETE16DWZ0zbb"
        PACKAGE_NAME: "com.hyperapp"
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install EAS CLI
        script: |
          npm install -g eas-cli@16.19.1
      - name: Configure EAS project
        script: |
          eas login --token $EXPO_TOKEN
          eas build:configure
      - name: Build Android APK
        script: |
          eas build -p android --profile production --non-interactive
    artifacts:
      - build/**/*.apk
      - build/**/*.aab
    publishing:
      email:
        recipients:
          - fatehielbaradei2030@gmail.com
        notify:
          success: true
          failure: true