workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 120
    environment:
      node: 18.17.0
      npm: 9.6.7
      java: 17
      ndk: r23b
      vars:
        EXPO_TOKEN: "VkNJEL0mNvRoV36R5vDeYPT4eSLJETE16DWZ0zbb"
        PACKAGE_NAME: "com.hyperapp"
    scripts:
      - name: Clean node modules & install
        script: |
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps

      - name: Build Expo app via EAS
        script: |
          npx eas-cli build --platform android --profile production --non-interactive

    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab

    publishing:
      email:
        recipients:
          - fatehielbaradei2030@gmail.com
        notify:
          success: true
          failure: true