workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 120
    environment:
      node: 18
      npm: 9
      vars:
        EXPO_TOKEN: VkNJEL0mNvRoV36R5vDeYPT4eSLJETE16DWZ0zbb
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Install EAS CLI
        script: |
          npm install -g eas-cli --legacy-peer-deps
      - name: Build Android APK
        script: |
          eas build --platform android --profile production --non-interactive
    artifacts:
      - build/**/app-*.apk
      - build/**/app-*.aab
    publishing:
      email:
        recipients:
          - fatehielbaradei2030@gmail.com
        notify:
          success: true
          failure: true
