workflows:
  expo-workflow:
    name: Expo App Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      node: 20
      vars:
        EXPO_TOKEN: Encrypted(...) # optional if you want to use EAS cloud builds
    scripts:
      - name: Install dependencies
        script: npm install --legacy-peer-deps
      - name: Build Android APK
        script: npx expo build:android -t apk
      - name: Build Android AAB
        script: npx expo build:android -t app-bundle
      - name: Build iOS IPA
        script: npx expo build:ios -t archive
    artifacts:
      - dist/**/*.apk
      - dist/**/*.aab
      - dist/**/*.ipa
