workflows:
  expo-workflow:
    name: Expo App Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        NODE_VERSION: 20
      node: $NODE_VERSION
      npm: true
      expo: true
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build Android APK
        script: npx expo build:android -t apk
      - name: Build Android AAB
        script: npx expo build:android -t app-bundle
      - name: Build iOS IPA
        script: npx expo build:ios -t archive
    artifacts:
      - build/**/*.apk
      - build/**/*.aab
      - build/**/*.ipa
