scripts:
- name: Configure EAS
  script: |
    # Set EAS project ID (you'll need to get this from your Expo account)
    export EXPO_TOKEN=VkNJEL0mNvRoV36R5vDeYPT4eSLJETE16DWZ0zbb
    npx eas-cli@latest whoami || npx eas-cli@latest login --non-interactive
    
- name: Build Android APK
  script: |
    npx eas-cli@latest build --platform android --profile production --local --output ./app-release.apk --non-interactive
