workflows:
  expo-android-apk:
    name: Expo Android Build
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      node: 20
      vars:
        # Add your Expo token in Codemagic dashboard -> Environment variables
        EXPO_TOKEN: Encrypted(...) 

    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Install EAS CLI
        script: |
          npm install -g eas-cli
      - name: Build Android APK
        script: |
          npx eas-cli build -p android --profile preview --output ./app-release.apk

    artifacts:
      - ./app-release.apk
