workflows:
android-workflow:
  name: Android Build
  max_build_duration: 60
  environment:
    android_signing:
      - keystore_reference
    groups:
      - google_play
    vars:
      PACKAGE_NAME: "com.yourcompany.hyperapp"
    node: 18.17.0
    npm: 9.6.7
    ndk: r23b
    java: 17
  scripts:
    - name: Install npm dependencies
      script: |
        npm install
    - name: Install Expo CLI
      script: |
        npm install -g expo-cli
    - name: Set up local properties
      script: |
        echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
    - name: Build Android APK
      script: |
        cd android
        ./gradlew assembleRelease
  artifacts:
    - android/app/build/outputs/**/*.apk
    - android/app/build/outputs/**/*.aab
  publishing:
    email:
      recipients:
        - fatehielbaradei2030@gmail.com
      notify:
        success: true
        failure: true
