workflows:
android-workflow:
  name: Android Build
  max_build_duration: 60
  environment:
    node: 18.19.0
    groups:
      - android_credentials
    vars:
      EXPO_PUBLIC_SUPABASE_URL: "https://irbjqbmzohavhhdflsip.supabase.co"
      EXPO_PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlyYmpxYm16b2hhdmhoZGZsc2lwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMzE1NDMsImV4cCI6MjA2NzgwNzU0M30.XS1bZySIL4MF9GI0oak_zYHKLE-1kmTEKmW7tJH0flw"
  scripts:
    - name: Install npm dependencies
      script: |
        npm install
    
    - name: Install EAS CLI
      script: |
        npm install -g eas-cli
    
    - name: Setup Expo
      script: |
        npx expo-doctor
    
    - name: Prebuild Android
      script: |
        npx expo prebuild --platform android --clean
    
    - name: Build Android APK
      script: |
        cd android
        ./gradlew assembleRelease
  
  artifacts:
    - android/app/build/outputs/apk/release/*.apk
  
  publishing:
    email:
      recipients:
        - fatehielbaradei2030@gmail.com
      notify:
        success: true
        failure: true
