workflows:
  expo-android-apk:
    name: Expo Android Build
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      node: 20
      npm: 9
      vars:
        EXPO_TOKEN: VkNJEL0mNvRoV36R5vDeYPT4eSLJETE16DWZ0zbb

    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Install EAS CLI
        script: |
          npm install -g eas-cli
      - name: Build Android APK (remote)
        script: |
          npx eas-cli build -p android --profile preview --non-interactive

    artifacts:
      - build/**/android/**/*.apk
