workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      node: 18.17.0
      npm: 9.6.7
      java: 17
      android_signing:
        - keystore_reference
      vars:
        EXPO_TOKEN: VkNJEL0mNvRoV36R5vDeYPT4eSLJETE16DWZ0zbb
        PACKAGE_NAME: "com.hyperapp"
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Install Expo CLI
        script: |
          npm install -g eas-cli
      - name: Build Android APK
        script: |
          eas build --platform android --profile production --non-interactive
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - fatehielbaradei2030@gmail.com
        notify:
          success: true
          failure: true