workflows:
android-workflow:
  name: Android Build
  max_build_duration: 60
  environment:
    android_signing:
      - keystore_reference
    groups:
      - google_play
    vars:
      PACKAGE_NAME: "com.pulse.app"
    node: 18.20.3
    npm: 10.2.3
    xcode: latest
    cocoapods: default
  scripts:
    - name: Install npm dependencies
      script: |
        npm ci --legacy-peer-deps
    
    - name: Install Expo CLI
      script: |
        npm install -g expo-cli@latest
        npm install -g eas-cli@latest
    
    - name: Setup Android SDK
      script: |
        echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
    
    - name: Prebuild Android
      script: |
        npx expo prebuild --platform android --clear
    
    - name: Build Android APK
      script: |
        cd android
        ./gradlew assembleRelease
    
    - name: Build Android AAB
      script: |
        cd android
        ./gradlew bundleRelease
  artifacts:
    - android/app/build/outputs/**/*.apk
    - android/app/build/outputs/**/*.aab
    - android/app/build/outputs/**/mapping.txt
  publishing:
    email:
      recipients:
        - user@example.com
      notify:
        success: true
        failure: true
    google_play:
      credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
      track: internal
      submit_as_draft: true
