workflows:
  expo-workflow:
    name: Expo Android Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      node: 20
    scripts:
      - name: Install dependencies
        script: npm install --legacy-peer-deps
      - name: Build Android APK
        script: npx eas build -p android --profile preview --local --output ./app-release.apk
    artifacts:
      - ./app-release.apk
