workflows:
  android-apk-build:
    name: Android APK Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      node: 20
      npm: 9
      vars:
        EXPO_TOKEN: $EXPO_TOKEN  # make sure you have set this in Codemagic
    scripts:
      - name: Clean environment
        script: |
          echo "Cleaning npm cache and removing old node_modules"
          npm cache clean --force
          rm -rf node_modules package-lock.json
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Verify node_modules
        script: |
          ls node_modules | head -20
      - name: Build APK
        script: |
          npx eas build --platform android --profile apk-build --non-interactive
    artifacts:
      - build/**/app-*.apk
