name: Android APK Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4   # updated from v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4   # updated from v2
        with:
          distribution: temurin
          java-version: 17

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps

      - name: Build Android Release
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4   # updated from v3
        with:
          name: android-build
          path: android/app/build/outputs/apk/release/app-release.apk
